# Generated by Django 4.1.2 on 2023-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('action', 'action'), ('classics', 'classics'), ('comic', 'comic'), ('mystery', 'mystery'), ('fantacy', 'fantacy'), ('fiction', 'fiction'), ('horror', 'horror'), ('literary', 'literary'), ('nonfiction', 'nonfiction')], default='classics', max_length=100),
        ),
    ]
